In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

from matplotlib import pyplot as plt

In [2]:
data = Path('../data/with_pop.csv')
info = pd.read_csv(data)
info.head()

track_popularity playlist_genre playlist_subgenre  danceability  energy  \
0              66.0            pop         dance pop         0.748   0.916   
1              67.0            pop         dance pop         0.726   0.815   
2              70.0            pop         dance pop         0.675   0.931   
3              60.0            pop         dance pop         0.718   0.930   
4              69.0            pop         dance pop         0.650   0.833   

    key  loudness  mode  speechiness  acousticness  instrumentalness  \
0   6.0    -2.634   1.0       0.0583        0.1020          0.000000   
1  11.0    -4.969   1.0       0.0373        0.0724          0.004210   
2   1.0    -3.432   0.0       0.0742        0.0794          0.000023   
3   7.0    -3.778   1.0       0.1020        0.0287          0.000009   
4   1.0    -4.672   1.0       0.0359        0.0803          0.000000   

   liveness  valence  
0    0.0653    0.518  
1    0.3570    0.693  
2    0.1100    0.613  
3    0.2040    0.277  
4    0.0833    0.725

In [3]:
pop_df = info.drop(columns=['playlist_genre', 'playlist_subgenre'])
pop_df

track_popularity  danceability  energy   key  loudness  mode  \
0                  66.0         0.748   0.916   6.0    -2.634   1.0   
1                  67.0         0.726   0.815  11.0    -4.969   1.0   
2                  70.0         0.675   0.931   1.0    -3.432   0.0   
3                  60.0         0.718   0.930   7.0    -3.778   1.0   
4                  69.0         0.650   0.833   1.0    -4.672   1.0   
...                 ...           ...     ...   ...       ...   ...   
27585              42.0         0.428   0.922   2.0    -1.814   1.0   
27586              20.0         0.522   0.786   0.0    -4.462   1.0   
27587              14.0         0.529   0.821   6.0    -4.899   0.0   
27588              15.0         0.626   0.888   2.0    -3.361   1.0   
27589              27.0         0.603   0.884   5.0    -4.571   0.0   

       speechiness  acousticness  instrumentalness  liveness  valence  
0           0.0583      0.102000          0.000000    0.0653   0.5180  
1           0.0373      0.072400          0.004210    0.3570   0.6930  
2           0.0742      0.079400          0.000023    0.1100   0.6130  
3           0.1020      0.028700          0.000009    0.2040   0.2770  
4           0.0359      0.080300          0.000000    0.0833   0.7250  
...            ...           ...               ...       ...      ...  
27585       0.0936      0.076600          0.000000    0.0668   0.2100  
27586       0.0420      0.001710          0.004270    0.3750   0.4000  
27587       0.0481      0.108000          0.000001    0.1500   0.4360  
27588       0.1090      0.007920          0.127000    0.3430   0.3080  
27589       0.0385      0.000133          0.341000    0.7420   0.0894  

[27590 rows x 11 columns]

# Accuracy Change

In [4]:
#changed the bins and saw accuracy greatly improve

In [1]:
pop_df.loc[pop_df['track_popularity'] < 50, 'track_popularity'] = 0
pop_df.loc[(pop_df['track_popularity'] >= 50), 'track_popularity'] = 1

In [5]:
#pop_df.loc[pop_df['track_popularity'] < 35, 'track_popularity'] = 0
#pop_df.loc[(pop_df['track_popularity'] >= 35) & (pop_df['track_popularity'] < 75), 'track_popularity'] = 1
#pop_df.loc[pop_df['track_popularity'] >=75, 'track_popularity']= 2

In [6]:
#pop_df.loc[pop_df['track_popularity'] < 50, 'track_popularity'] = 0
#pop_df.loc[(pop_df['track_popularity'] >= 50) & (pop_df['track_popularity'] < 75), 'track_popularity'] = 1
#pop_df.loc[pop_df['track_popularity'] >=75, 'track_popularity']= 2

In [7]:
pop_df

track_popularity  danceability  energy   key  loudness  mode  \
0                   1.0         0.748   0.916   6.0    -2.634   1.0   
1                   1.0         0.726   0.815  11.0    -4.969   1.0   
2                   1.0         0.675   0.931   1.0    -3.432   0.0   
3                   1.0         0.718   0.930   7.0    -3.778   1.0   
4                   1.0         0.650   0.833   1.0    -4.672   1.0   
...                 ...           ...     ...   ...       ...   ...   
27585               1.0         0.428   0.922   2.0    -1.814   1.0   
27586               0.0         0.522   0.786   0.0    -4.462   1.0   
27587               0.0         0.529   0.821   6.0    -4.899   0.0   
27588               0.0         0.626   0.888   2.0    -3.361   1.0   
27589               0.0         0.603   0.884   5.0    -4.571   0.0   

       speechiness  acousticness  instrumentalness  liveness  valence  
0           0.0583      0.102000          0.000000    0.0653   0.5180  
1           0.0373      0.072400          0.004210    0.3570   0.6930  
2           0.0742      0.079400          0.000023    0.1100   0.6130  
3           0.1020      0.028700          0.000009    0.2040   0.2770  
4           0.0359      0.080300          0.000000    0.0833   0.7250  
...            ...           ...               ...       ...      ...  
27585       0.0936      0.076600          0.000000    0.0668   0.2100  
27586       0.0420      0.001710          0.004270    0.3750   0.4000  
27587       0.0481      0.108000          0.000001    0.1500   0.4360  
27588       0.1090      0.007920          0.127000    0.3430   0.3080  
27589       0.0385      0.000133          0.341000    0.7420   0.0894  

[27590 rows x 11 columns]

In [8]:
X = pop_df.copy()
X.drop("track_popularity", axis=1, inplace=True)
X.head()

danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.748   0.916   6.0    -2.634   1.0       0.0583        0.1020   
1         0.726   0.815  11.0    -4.969   1.0       0.0373        0.0724   
2         0.675   0.931   1.0    -3.432   0.0       0.0742        0.0794   
3         0.718   0.930   7.0    -3.778   1.0       0.1020        0.0287   
4         0.650   0.833   1.0    -4.672   1.0       0.0359        0.0803   

   instrumentalness  liveness  valence  
0          0.000000    0.0653    0.518  
1          0.004210    0.3570    0.693  
2          0.000023    0.1100    0.613  
3          0.000009    0.2040    0.277  
4          0.000000    0.0833    0.725

In [9]:
y = pop_df['track_popularity'].ravel()


# Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [11]:
X_train, X_test, y_train, y_test, = train_test_split(X, y, test_size = 0.2, random_state=42)

In [12]:
scaler = StandardScaler()

In [13]:
X_scaler = scaler.fit(X_train)

In [14]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
model = RandomForestClassifier(n_estimators=1000, random_state=42)

In [16]:
model = model.fit(X_train_scaled, y_train)

In [17]:
predictions = model.predict(X_test_scaled)
predictions

array([1., 1., 1., ..., 1., 1., 2.])

In [18]:
y_test

array([1., 1., 0., ..., 1., 0., 2.])

In [19]:
from sklearn.metrics import make_scorer, accuracy_score, roc_auc_score

accuracy_score(y_test, predictions)


0.761689017760058

In [20]:
results = pd.DataFrame({'Expected Popularity': predictions})

In [21]:
test_df = pd.DataFrame(X_test_scaled)

In [22]:
test_df = test_df.join(results)

In [23]:
test_df

0         1         2         3         4         5         6  \
0     0.488737 -0.525032  1.011044 -1.186538 -1.144339 -0.776572  0.191514   
1     1.287836 -1.631401  1.011044 -1.151229  0.873867 -0.511761  0.039092   
2    -0.041700  0.288150 -0.927795 -1.060433  0.873867  1.808535  1.563312   
3    -0.089922 -2.278628  0.180113 -2.146618  0.873867 -0.690927  2.917178   
4     1.336058 -0.436522 -0.096864  0.018353 -1.144339 -0.071722 -0.606460   
...        ...       ...       ...       ...       ...       ...       ...   
5513  0.392294 -1.338213 -0.096864 -0.519695  0.873867 -0.784448 -0.416829   
5514 -0.282808 -0.060356  0.180113  0.193219 -1.144339 -0.795276 -0.553561   
5515  1.053617  0.387724  0.734067  0.081574  0.873867 -0.356222  0.294623   
5516  1.384279 -1.797357  1.564998 -2.310050  0.873867 -0.110115  0.267725   
5517  0.350961 -2.804154  1.011044 -0.750047 -1.144339 -0.640721  3.078566   

             7         8         9  Expected Popularity  
0     0.293292 -0.588593  1.235100                  1.0  
1    -0.361722 -0.534570  1.286875                  1.0  
2    -0.313973  1.382584 -0.007491                  1.0  
3     1.420938 -0.709156  1.748532                  1.0  
4    -0.362961 -0.767791 -0.352655                  1.0  
...        ...       ...       ...                  ...  
5513 -0.362961 -0.527982 -0.451890                  2.0  
5514 -0.251583  1.013647  0.074486                  1.0  
5515 -0.359268 -0.878472  1.455142                  1.0  
5516 -0.362930 -0.825767  0.527514                  1.0  
5517 -0.362961 -0.726286 -0.818627                  2.0  

[5518 rows x 11 columns]

In [24]:
final = test_df.rename(columns={0: "danceability", 1: "energy", 2: "key", 
                                3: "loudness", 4: "mode", 5: "speechiness", 6: "acousticness",
                                7: "instrumentalness", 8: "liveness", 9: "valence"})
final.head()

danceability    energy       key  loudness      mode  speechiness  \
0      0.488737 -0.525032  1.011044 -1.186538 -1.144339    -0.776572   
1      1.287836 -1.631401  1.011044 -1.151229  0.873867    -0.511761   
2     -0.041700  0.288150 -0.927795 -1.060433  0.873867     1.808535   
3     -0.089922 -2.278628  0.180113 -2.146618  0.873867    -0.690927   
4      1.336058 -0.436522 -0.096864  0.018353 -1.144339    -0.071722   

   acousticness  instrumentalness  liveness   valence  Expected Popularity  
0      0.191514          0.293292 -0.588593  1.235100                  1.0  
1      0.039092         -0.361722 -0.534570  1.286875                  1.0  
2      1.563312         -0.313973  1.382584 -0.007491                  1.0  
3      2.917178          1.420938 -0.709156  1.748532                  1.0  
4     -0.606460         -0.362961 -0.767791 -0.352655                  1.0

In [ ]:
final.to_csv('../data/predicted.csv', index=False)

In [25]:
pop_df

track_popularity  danceability  energy   key  loudness  mode  \
0                   1.0         0.748   0.916   6.0    -2.634   1.0   
1                   1.0         0.726   0.815  11.0    -4.969   1.0   
2                   1.0         0.675   0.931   1.0    -3.432   0.0   
3                   1.0         0.718   0.930   7.0    -3.778   1.0   
4                   1.0         0.650   0.833   1.0    -4.672   1.0   
...                 ...           ...     ...   ...       ...   ...   
27585               1.0         0.428   0.922   2.0    -1.814   1.0   
27586               0.0         0.522   0.786   0.0    -4.462   1.0   
27587               0.0         0.529   0.821   6.0    -4.899   0.0   
27588               0.0         0.626   0.888   2.0    -3.361   1.0   
27589               0.0         0.603   0.884   5.0    -4.571   0.0   

       speechiness  acousticness  instrumentalness  liveness  valence  
0           0.0583      0.102000          0.000000    0.0653   0.5180  
1           0.0373      0.072400          0.004210    0.3570   0.6930  
2           0.0742      0.079400          0.000023    0.1100   0.6130  
3           0.1020      0.028700          0.000009    0.2040   0.2770  
4           0.0359      0.080300          0.000000    0.0833   0.7250  
...            ...           ...               ...       ...      ...  
27585       0.0936      0.076600          0.000000    0.0668   0.2100  
27586       0.0420      0.001710          0.004270    0.3750   0.4000  
27587       0.0481      0.108000          0.000001    0.1500   0.4360  
27588       0.1090      0.007920          0.127000    0.3430   0.3080  
27589       0.0385      0.000133          0.341000    0.7420   0.0894  

[27590 rows x 11 columns]

In [26]:
X_test_scaled

array([[ 0.48873669, -0.52503152,  1.0110439 , ...,  0.29329216,
        -0.58859311,  1.23510022],
       [ 1.28783614, -1.63140141,  1.0110439 , ..., -0.36172225,
        -0.5345702 ,  1.28687485],
       [-0.04170002,  0.28815036, -0.92779519, ..., -0.31397291,
         1.38258439, -0.00749081],
       ...,
       [ 1.05361734,  0.38772365,  0.73406689, ..., -0.35926823,
        -0.87847216,  1.45514239],
       [ 1.38427918, -1.7973569 ,  1.56499793, ..., -0.36293026,
        -0.82576688,  0.52751366],
       [ 0.35096092, -2.8041535 ,  1.0110439 , ..., -0.36296081,
        -0.72628566, -0.81862663]])

# Logistical Regression

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [28]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier

LogisticRegression(random_state=1)

In [29]:
classifier.fit(X_train, y_train)

C:\Users\MSI\Anaconda\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [30]:
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

Prediction  Actual
0            1.0     1.0
1            1.0     2.0
2            1.0     0.0
3            1.0     1.0
4            1.0     1.0
...          ...     ...
6893         1.0     1.0
6894         1.0     1.0
6895         1.0     1.0
6896         1.0     1.0
6897         1.0     1.0

[6898 rows x 2 columns]

In [31]:
accuracy_score(y_test, predictions)

0.6767178892432589